services:
  video-service:
    build: .
    image: ghcr.io/langrenn-sprint/video-service:test
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - EVENTS_HOST_SERVER=event-service
      - EVENTS_HOST_PORT=8080
      - PHOTOS_HOST_SERVER=photo-service
      - PHOTOS_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_STORAGE_BUCKET=${GOOGLE_STORAGE_BUCKET}
      - GOOGLE_STORAGE_SERVER=${GOOGLE_STORAGE_SERVER}
      - MODE=CAPTURE
