name: Test, build and deploy server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, test and deploy to GitHub Container registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.8.13"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: |
          uv run poe release
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      #- name: Log in to registry
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      #- name: Build and push multi-arch image
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
      #  run: |
      #    docker buildx build \
      #      --platform linux/amd64,linux/arm64 \
      #      --tag ghcr.io/langrenn-sprint/video-service:latest \
      #      --push .
